name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to checkout'
        required: false
        default: 'main'
        type: string

concurrency:
  group: "${{ github.workflow }} @ ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Debug info
        run: |
          cat <<EOF
          Branch to checkout: ${{ inputs.branch || 'main' }}
          Triggered by: ${{ github.actor }}
          Working directory: $(pwd)
          Node version: $(node --version)
          NPM version: $(npm --version)
          EOF

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.nvmrc'

      - name: Install system library dependencies
        run: |
          echo "Using pkg-config $(pkg-config --version)"
          # These dependencies are from scratch-paint -> paper.js -> canvas
          # See also `util/has_lib.js` in the `canvas` package
          # There must be a better way to detect gif_lib.h than this...
          missing_libraries="$(
            ldconfig -p | grep -q 'libcairo\.so' || echo libcairo2-dev
            pkg-config pangocairo || echo libpango1.0-dev
            pkg-config libssl || echo libssl-dev
            pkg-config libjpeg || echo libjpeg-dev
            test -f /usr/include/gif_lib.h || echo libgif-dev
          )"
          echo "Missing libraries: [$missing_libraries]"
          if [ -n "$missing_libraries" ]; then
            sudo apt update # avoiding this is the main reason for detecting missing libraries
            sudo apt install -y $missing_libraries
          else
            echo "No missing libraries"
          fi

      - name: Install NPM dependencies (no cache)
        run: NODE_ENV=development npm ci

      - name: Build packages
        run: npm run build

      - name: Store build artifacts
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: build
          path: |
            packages/**/build
            packages/**/dist
            packages/**/playground

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Config GitHub user
        shell: bash
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@localhost'

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.branch || 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: build
          path: packages

      - name: Deploy scratch-gui to GitHub Pages (editor/)
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/scratch-gui/build
          destination_dir: editor
          keep_files: false
          force_orphan: true
          full_commit_message: "Deploy editor from ${{ inputs.branch || 'main' }} branch - Build for ${{ github.sha }}"
